#spring.application.name=springboot-mybatis-quickstart

#配置数据库的连接信息
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3307/db01
#spring.datasource.username=root
#spring.datasource.password=你的数据库密码
#指定数据库连接池为druid连接池
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

#开启mybatis日志输出
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#指定xml映射文件的位置
#mybatis.mapper-locations=classpath:com/uestc/mapper/*.xml



#（MyBatis VS JDBC）JDBC的缺点:
#     1.硬编码：配置信息在代码中硬编码，不灵活
#     2.代码繁杂
#     3.资源浪费：每个数据库操作都需要创建和关闭连接，浪费资源（mybatis采用数据库连接池，默认Hikari）

#hikari和druid的对比
#     1.hikari：追求性能，低延迟
#     2.druid：追求功能，提供丰富的监控功能